name: hc_web
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.0-82.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.1
  url_launcher: ^6.2.6
  google_fonts:  ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_flutter_team_lints: ^2.1.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  assets:
    - lib/assets/logo.png
    - lib/assets/images/ds.png

flutter_launcher_icons:
  web:
    generate: true
    image_path: "lib/assets/logo.png"
    background_color: "#FFFFFF"
    theme_color: "#009CFF"
