name: hc_web
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0-82.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.1
  url_launcher: ^6.2.6
  google_fonts:  ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_flutter_team_lints: ^2.1.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/logo_flipped.png
    - assets/images/ds.png
    - assets/images/explore/feeling_arrow.webp
    - assets/images/explore/how_we_feel.webp
    - assets/images/explore/introducktion.webp
    - assets/images/explore/peppy_pals.webp
    - assets/images/explore/messenger.webp
    - assets/images/explore/mira_gosha.png
    - assets/images/explore/pluck_it.webp
    - assets/images/home/learning-kids-with-father.jpg
    - assets/images/home/learning-kids-with-mother.png
    - assets/images/team/team.jpg

flutter_launcher_icons:
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#FFFFFF"
    theme_color: "#FFC107"
