name: hc_web
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.0-82.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.1
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  layerlens: any

flutter:
  uses-material-design: true
